config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "categories#index"
  resources :users, only:[:update,:edit]
  resources :categories, only:[:index,:create,:edit,:update,:destroy] do
    resources :tasks, only:[:index,:create,:destroy]
  end
  # devise_scope :user do
  #   get 'login', to: 'devise/sessions#new'
  #   post 'login', to: 'devise/sessions#create'
  #   delete 'signout', to: 'devise/sessions#destroy'
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks,dependent: :destroy

  validates :cat_name, presence:true, length: { maximum:7 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :category
  
  validates :task_name,presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthabl
  has_many :categories,dependent: :destroy
  has_many :tasks,dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action:configure_permitted_parameters,if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  # def current_user
  #   @current_user ||= User.find_by(id: session[:id])
  # end
   
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Category.new
    @user = current_user
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_tasks_path(@category), notice: 'カテゴリーが作成されました'
    else
      flash[:notice] = "失敗しました"
      render :index
    end
  end

  def edit
    @category = Category.find_by(id:params[:id])
  end
  
  def update
    @category = Category.find_by(id:params[:id])
    if @category.update(category_params)
      redirect_to category_tasks_path(@category),notice: 'カテゴリーが編集されました'
    else
      render :edit
    end
  end

  def destroy
    @category=Category.find_by(params[:id])
    @category.destroy
    render :index
  end

  private
  def category_params
    params.require(:category).permit(:cat_name).merge(user_id:current_user.id)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_category
  def index
    @task = Task.new
    @tasks = @category.tasks.order(deadline: :asc)
    @category1 = Category.find(params[:category_id])
    @category = Category.new
  end

  def create
    @task = @category.tasks.new(task_params)
    if @task.save
      # flash[:notice] = 'タスクが追加されました'
      respond_to do |format|
        format.html {redirect_to  category_tasks_path(@category), notice: 'タスクが追加されました'}
        format.json
      end
    else
      @tasks = @category.tasks
      flash.now[:alert] = "メッセージを入力してください"
      render :index
    end
  end

  def destroy
    @task=Task.find(params[:id])
    @task.destroy
    redirect_to  category_tasks_path(@category), notice: 'タスクが削除されました'
  end

  private

  def task_params
    params.require(:task).permit(:task_name,:deadline).merge(user_id:current_user.id)
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  GET /resource/confirmation/new
  def new
    super
  end

  POST /resource/confirmation
  def create
    super
  end

  GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  GET /resource/password/new
  def new
    super
  end

  POST /resource/password
  def create
    super
  end

  GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  GET /resource/sign_up
  def new
    super
  end

  POST /resource
  def create
    super
  end

  GET /resource/edit
  def edit
    super
  end

  PUT /resource
  def update
    super
  end

  DELETE /resource
  def destroy
    super
  end

  GET /resource/cancel
  Forces the session data which is usually expired after sign
  in to be expired now. This is useful if the user wants to
  cancel oauth signing in/up in the middle of the process,
  removing all OAuth session data.
  def cancel
    super
  end

  protected

  If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  GET /resource/sign_in
  def new
    super
  end

  POST /resource/sign_in
  def create
    super
  end

  DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  GET /resource/unlock/new
  def new
    super
  end

  POST /resource/unlock
  def create
    super
  end

  GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  protected

  The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def edit
  end

  private
  
  def user_params
    params.require(:user).permit(:name,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.haml
.task-side
  .tasks
    -current_user.categories.each do|category|
      .task__box
        .task__box__name
          = link_to category_tasks_path(category) do
            = fa_icon 'list', class: 'choise' 
            =category.cat_name
        .task__box__edit
          = link_to  edit_category_path(category.id) do
            = fa_icon 'pencil', class: 'pen' 
  .header
    %a#fadetoggle_button{:href => "#"} ＋
.task
  .task__edit
    .account-page__inner--right.user-form
    = form_for(@category) do |f|
      .field
        .field-label
          = f.label :name
        .field-input
          = f.text_field :cat_name
      .actions
        = f.submit "Update", class: 'btn'

    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'link'
    = link_to "カテゴリー削除",category_path, method: :delete, class: 'link'

app/views/categories/index.html.haml
= render 'tasks/side_bar'
.task

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TaskApp
    = csrf_meta_tags
    -# = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    .header
      .header__title
        = link_to "TO-DO APP", root_path, class:'todo'
      .header__right
        - if user_signed_in?
          = link_to current_user.name, edit_user_path(current_user), class: "header__right__btn__2"
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right__btn"
        - else
          = link_to "ログイン", new_user_session_path, class: "header__right__btn__2"
          = link_to "新規登録", new_user_registration_path, class: "header__right__btn"
          
    .conetnts
    = yield

app/views/task/_side_bar.html.haml
.task-side
  .tasks
    -current_user.categories.each do|category|
      .task__box
        .task__box__name
          = link_to "categories" do
            = fa_icon 'list', class: 'choise' 
            =category.cat_name
        .task__box__edit
          = fa_icon 'pencil', class: 'pen' 
  .header
    %a#fadetoggle_button{:href => "#"} ＋
    .form
      = form_for [@category],html:{id:'fadetoggle_menu'} do |f|
        = f.text_field :cat_name, class: 'form__message', placeholder: 'Add category'
        = f.submit 'Send', class: 'form__submit'

app/views/tasks/_side_bar.html.haml
.task-side
  .tasks
    -current_user.categories.each do|category|
      .task__box
        .task__box__name
          = link_to category_tasks_path(category) do
            = fa_icon 'list', class: 'choise' 
            =category.cat_name
        .task__box__edit
          = link_to  edit_category_path(category.id) do
            = fa_icon 'pencil', class: 'pen' 
  .header
    %a#fadetoggle_button{:href => "#"} ＋
    .form
      = form_for [@category],action:'POST',html:{id:'fadetoggle_menu'} do |f|
        = f.text_field :cat_name, class: 'form__message', placeholder: 'Add category'
        = f.submit 'Send', class: 'form__submit'

app/views/tasks/_task.html.haml
.task
  .form
    .form__message
      =form_for [@category,@task],url:category_tasks_path,html:{id:'new_task'} do|f|
        =f.text_field :task_name, class: 'form__message', placeholder: "#{@category1.cat_name}のタスクを追加"
        .form__mask
          =f.label :deadline, class: 'form__mask__image' do
            = f.date_field :deadline, class: 'hidden'
          = f.submit 'Send', class: 'form__submit'   
  .works
    -@tasks.each do|task|
      .work
        .work__box
          =label_tag :check1,task.task_name
        .work__btn
          =task.deadline
          =link_to "削除",category_task_path(@category1.id,task), method: :delete,class:"icon"

app/views/tasks/index.html.haml
= render '/tasks/side_bar'
= render '/tasks/task'

app/views/users/edit.html.haml
.account-page
  .account-page__inner--left.account-page__header
    %h1 Edit Account
  .account-page__inner--right.user-form
    = form_for(current_user) do |f|
      .field
        .field-label
          = f.label :name
        .field-input
          = f.text_field :name, autofocus: true
      .field
        .field-label
          = f.label :email
        .field-input
          = f.email_field :email
      .actions
        = f.submit "Update", class: 'btn'

    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'link'
    = link_to "トップページに戻る", :back, class: 'link'